### ISSUE TITLE
The task fails if "newgat" and "dustjs-helper" are required together

### ISSUE THREAD

**Issue by ohpyupi** [aredridel/grunt-put-packages-in-requirejs-config#1]
Hi. My project requires 'dustjs-helper' module. However, it throws an error if I have "newgat" in my node_modules. If I remove "newgat" in the node_modules, the grunt job works perfectly fine. However, I do need "newgat" on my front-end code base. Does anyone why this happens and how to debug it? Thanks.

![Screen Shot 2020-01-06 at 9 50 42 AM](https://user-images.githubusercontent.com/17169119/71837066-5fca9500-306a-11ea-8dde-042ef80a4a56.png)

**Comment by aredridel** [comment]
@ohpyupi What's the actual error? From the screenshot it looks like there's just a warning and no error, what isn't working?

**Comment by ohpyupi** [comment]
@aredridel Maybe it's good to move this issue to `copy-browser-module` repo since that is where the error is thrown. Basically, the issue I am experiencing is that since `newgat` already has `dustjs-helper` as its dependency, if I add `dustjs-helper` to the task, `dustjs-helper` is considered to be duplicate package. And it just throws an error.

See the code here https://github.com/aredridel/copy-browser-modules/blob/609b54b4fcc767a5fb99c5d390e50d913ef48fd5/index.js#L39

**Comment by ohpyupi** [comment]
Will close this ticket since I opened it in another repo which looks more relevant place.
